### ISSUE TITLE
No terrain textures

### ISSUE THREAD

**Issue by PizzaLawyer420** [Wargus/war1gus#149] opened 2019-11-03 23:09 UTC
Version 2.4.2 does not show tileset/terrain textures. Building, units, gold mines and roads seem to be the only exceptions.

Tried two different disks for install, both showed the same errors.

Using Win 7.

**Comment by amigalover** [comment] 2020-04-04 14:37
It's on my one computer, too. Win10 x86 on an i7 mobile with Quadro NVS3100m. Latest nvidia driver from 2016, all other programs and games are working wonderful - only War1gus has thia graphic glitch. Options change to OpenGL or other resolution does not help.
Can I configure sth in any ini file or check / uncheck a hook somewhere?

**Comment by timfel** [comment] 2020-04-14 04:52
Sorry about that. I tried on 5 different computers here (Win10/Radeon, Win10/Nvidia, Win10/Intel, Ubuntu/Intel, Ubuntu/Nividia) and couldn't reproduce the issue, so I don't know what's wrong, yet. However, I fixed an issue that War1gus was ignoring your selection of rendering mode and always forced OpenGL. You should be able to use software mode now to get around this problem

**Comment by amigalover** [comment] 2020-04-28 16:20
Hello timfel, no reason to sorry about - it's a hobby project and should be fun :-)

With your new built 2.4.3 the OpenGL feature can be disabled an now the graphic ist working like a charm. Thank you very much!

**Comment by timfel** [comment] 2020-06-28 08:37
Fixed on master.

**Closed by timfel** 2020-06-28 08:37 UTC
